### ISSUE TITLE
Module missing/install issues

### ISSUE THREAD

**Issue by VillaCare** [Roomify/RfA#113]
User warning: The following module is missing from the file system: field_object. For information about how to fix this, see the documentation page. in _drupal_trigger_error_with_delayed_logging() (line 1138 of /homepages/40/d568653886/htdocs/clickandbuilds/roomify-accommodations/includes/bootstrap.inc).

How to resolve? New install done

**Comment by salvoscala** [comment]
Hi @VillaCare,
Did you make a fresh installation on the last packaged release (1.3.3) ?

**Comment by salvoscala** [comment]
Did you update the CER module manually?

**Comment by VillaCare** [comment]
Hi, just did a new fresh install, 1 issues with the htaccess file which does not let me log in, than when making some changes I can log in but when enter quick set up and select vacation rental set up a error comes up without code, also that there are security updates. 
Than I have only the option to delete this set up, it does not go on to a next step.

**Comment by VillaCare** [comment]
Hi, think I got is resolved hence did something wrong, the quick set up goes fine although I get a error which is not specified.

Nevertheless remain the issue with the htacess file which I got resolved thanks to a lady at 1and1 tech support.
