### ISSUE TITLE
Duplicate entry 'commerce_order'....

### ISSUE THREAD

**Issue by CosyStudios** [Roomify/RfA#125]
I'm trying to clarify steps to reproduce this error but it seems once it occurs, it means the commerce tables are out of sync with bat bookings and a fresh installation is needed.
Clearing all the relevant commerce tables clears it for a moment but does not fix it.

The following appears to occur after a previous anon order has been created before and cancelled, then in the same session, submitting the roomify_accomodation_booking_confirmation_form again.
The only difference I can see between my implementation to the roomify theme, is that I pull the form in via ajax and append it to each room.
(Ive done this by replicating the roomify_accommodation_booking module but basically replacing the page callback with an ajax one...

```
function fluxio_accomodation_booking_ajax_callback ($page_callback_result) {
	if (is_null(drupal_get_http_header('Content-Type'))) {
    drupal_add_http_header('Content-Type', 'text/html; charset=utf-8');
  }
  global $language;
  drupal_add_http_header('Content-Language', $language->language);

  $content = drupal_render($page_callback_result);
  $html = '' . drupal_get_js($scope = 'header') . '' . $content . '';
  print $html;

  drupal_page_footer();
}
```

This works fine and successfully creates the order but then sometimes eventually the following occurs through both my ajax form and when done via the original form accessed by the book_this button..

> PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'commerce_order-24-0-0-und' for key 'PRIMARY': INSERT INTO {field_data_commerce_order_total} (entity_type, entity_id, revision_id, bundle, delta, language, commerce_order_total_amount, commerce_order_total_currency_code, commerce_order_total_data) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7, :db_insert_placeholder_8); Array ( [:db_insert_placeholder_0] => commerce_order [:db_insert_placeholder_1] => 24 [:db_insert_placeholder_2] => 43 [:db_insert_placeholder_3] => commerce_order [:db_insert_placeholder_4] => 0 [:db_insert_placeholder_5] => und [:db_insert_placeholder_6] => 0 [:db_insert_placeholder_7] => GBP [:db_insert_placeholder_8] => a:1:{s:10:"components";a:1:{i:0;a:3:{s:4:"name";s:10:"base_price";s:5:"price";a:3:{s:6:"amount";i:0;s:13:"currency_code";s:3:"GBP";s:4:"data";a:0:{}}s:8:"included";b:1;}}} ) in field_sql_storage_field_storage_write() (line 514 of D:\Workspace\nhfclean\RfA\www\modules\field\modules\field_sql_storage\field_sql_storage.module)

Has anyone seen such a response? Can you recommend a best way to "reset/clean up" after this occurs?

**Comment by CosyStudios** [comment]
To clarify, Im up to date with 1.3.4

**Comment by CosyStudios** [comment]
Just noted , I believe this occurs when an anon order is created and the cart expiration time is reached..
At which point, the cart is destroyed but the commerce order is not, so that same user goes to add new items to their cart but a new order number isnt created.

**Comment by acrollet** [comment]
Hi @CosyStudios, thanks for reporting! Can you clarify, can the issue be reproduced on the default RfA distribution? Or only with the ajax callback?

**Comment by CosyStudios** [comment]
Sorry Adrian, i wont let this thread sleep but I'm unfortunately unable to find the time to do a complete rebuild right this second..
I'll get back to this as soon as I can!

**Comment by acrollet** [comment]
please re-open if reproducible with 1.5.0
