### ISSUE TITLE
Anonymous bookings redirected to homepage

### ISSUE THREAD

**Issue by flodaq** [Roomify/RfA#126]
When submitting a booking with an anonymous user from the review page, I get automatically redirected to the homepage and I don't reach the checkout page.

After reviewing the database, the BAT event is created as well as the commerce order. On the other hand, the BAT booking is not created.

I use the latest version of RfA but have been regularly updating from version 1.2.0.

**Comment by salvoscala** [comment]
Hi @flodaq, what you mean with the review page? Can you describe step to step how to reproduce the issue?
Thanks!

**Comment by flodaq** [comment]
Hi, here is my step by step. It concerns only anonymous users. For admins and standard users, I do not have the issue.

- from /fr/listing/23, I search for availability from 2017-03-15 to 2017-03-18 for 2 people
- on /fr/booking/2017-03-15/2017-03-18/32?group_size=2&property=23, I have the correct dates, nigths and price, I then click the 'Confirm booking' button. The following POST parameters are sent:
`start_date=2017-03-15+00%3A00%3A00.000000+3+UTC&end_date=2017-03-18+00%3A00%3A00.000000+3+UTC&nights=3&type_id=32&amount=40500&offer_amount=0&op=Confirmer+la+r%C3%A9servation&form_build_id=form-YLbhJJCZd5Tw9g1T-MA_2gM0_kSAhi473QvcNBVsxls&form_id=roomify_accommodation_booking_confirmation_form`

- I get the following HTTP response:
`HTTP/1.1 302 Found
[...]
Location: [...]/fr/checkout`

- My browser does the HTTP request:
`GET [...]/fr/checkout HTTP/1.1`

- But here is the problem, I receive a 302 redirect:
`HTTP/1.1 302 Found
[...]
Location: [...]/fr`

**Comment by flodaq** [comment]
Okay I am starting to understand the problem. The commerce_cart_checkout_router() function is responsible for the redirection to the homepage and it seems to be because the commerce_cart_order_load() function for anonymous user returns null in my case. I continue to work on the problem.

**Comment by flodaq** [comment]
I found the problem. The user with ID 0 has been deleted from the database. So not a RfA issue. You can close the issue. Sorry.

**Comment by salvoscala** [comment]
Thanks :)
