### ISSUE TITLE
Stripe TLS 1.2 Problems with patch (Unsupported SSL protocol version)

### ISSUE THREAD

**Issue by CosyStudios** [Roomify/RfA#139]
As you all well know, Stripe recently enforced new accounts to use tls 1.2
As a result in many scenario including Roomify, people have been patching the stripe php library to force curl to use tls1.2

I ensured I had updated openssl & libcurl to up to date versions etc and the stripe test php script confirmed "Supports tls 1.2" - great, yet when i processed a test checkout on my server I kept getting the following...

> Following error received when processing card Unexpected error communicating with Stripe. If this problem persists, let us know at support@stripe.com. (Network error [errno 35]: Unsupported SSL protocol version).

Digging around forums for ages led me to run [THIS ](https://gist.githubusercontent.com/olivierbellone/9f93efe9bd68de33e9b3a3afbd3835cf/raw/a9fb5c4f8b171dce9661a5a4d8777be46b4dbc37/tls_test.php) script 
which runs various tests and lastly sees what happens when you force curl to use tls 1.2 

Low and behold my output was:

> OS: Linux
uname: Linux srv.cosyweb.co.uk 2.6.18-028stab118.1 #1 SMP Thu Feb 12 16:43:22 MSK 2015 x86_64
PHP version: 5.6.27
curl version: 7.38.0
SSL version: OpenSSL/1.0.0
SSL version number: 0
OPENSSL_VERSION_NUMBER: 1000105f
TLS test (default): TLS 1.2
TLS test (TLS_v1): TLS 1.2
**TLS test (TLS_v1_2): Error! errno = 35, msg = Unsupported SSL protocol version**

This confirms by default my server uses 1.2, when asked to use v1, it runs 1.2 BUT if forced to use 1.2 > you get the error above.

If this the case for you, 
REMOVE THE OFFENDING PATCH (lines 325-332 in stripe-php/lib/Stripe/ApiRequestor.php)
`/*if (OPENSSL_VERSION_NUMBER >= 0x1000100f) {
        if (!defined('CURL_SSLVERSION_TLSv1_2')) {
            // Note the value 6 comes from its position in the enum that
            // defines it in cURL's source code.
            define('CURL_SSLVERSION_TLSv1_2', 6); // constant not defined in PHP < 5.5
        }
        $opts[CURLOPT_SSLVERSION] = CURL_SSLVERSION_TLSv1_2;
    }*/`

Et voila/ - works!

**Comment by CosyStudios** [comment]
Solved

**Comment by acrollet** [comment]
@CosyStudios thanks for letting folks know!

**Comment by CosyStudios** [comment]
No worries Adrian, had to get that on the issue list.. drove me mad for a good 4 hours!

**Comment by acrollet** [comment]
sounds as bad as when I was trying to debug it for the patch!

**Comment by CosyStudios** [comment]
Apologies if its unclear in any way.. I could do with some sleep (its 4am here)

**Comment by CosyStudios** [comment]
Quite yes.
The last project i did with stripe last summer introduced the issue and i had to bugger about with woocommerce and someone elses out of date server to fix it..
So luckily i was preinformed of the issue and dug straight in assuming my server too had the same issue, but turns out certains linux distros dont like the force patch

**Comment by CosyStudios** [comment]
All the best..

**Comment by CosyStudios** [comment]
Should have our roomify implementation live in the next couple of days! :)
Ill let you know when its live,.

**Comment by acrollet** [comment]
cool! excited to see it.

**Comment by CosyStudios** [comment]
Had a hard time "breaking" the distro to our mould, but learnt alot re features overides etc

The only thing i had a real problem with was adding additional views handlers to roomify_listing, couldnt find a way to hook extra ones in so for mean time, ive had to copy the roomify_listing module and modify to my needs-since so many other modules referenced roomify_listing.

 Not upgrade perfect but stable for now!

**Comment by CosyStudios** [comment]
Did manage to make quite a useful mod to roomify_listings book_this field though which ill try and push up branch for you later...

To check if the room being searched for by dates is in fact in your cart and display "this is in your reservation" - rather than "unavailable for these dates"

**Comment by CosyStudios** [comment]
Sorry, irrelevant conversation in an issue....

**Comment by acrollet** [comment]
no worries! Always happy to hear how people are using the distro...

**Comment by CosyStudios** [comment]
Cool..
Right then, more issue to fix before the morning deadline !

**Comment by acrollet** [comment]
best of luck...

**Comment by CosyStudios** [comment]
Huzaa, the site is now live!
https://thelodgesnhf.com

Booking/checkout functionality is currently disabled whilst the owners get on their feet but the date search still reveals availability and each room has an availbility calendar that opens up :)

**Comment by CosyStudios** [comment]
The terrible logo was not my responsibility
