### ISSUE TITLE
Update Existing bookings to the new references.

### ISSUE THREAD

**Issue by salvoscala** [Roomify/RfA#154]
We should update existing bookings and reference a user to each one.

-  Standard Bookings
If it hasn’t a Billing Profile associated we should create a new user (with a dummy email).
If it has a profile:
If the billing profile owner is only a guest, reference the booking to that user;
If the billing profile owner is a property owner or a Roomify Manager, let’s create a dummy user and grab data from the billing profile.

-  Booking.com
If the booking has an email field filled we should create (or check for an existing user with that email) a new user and reference that to the booking.

-  iCal Bookings
Create always a dummy user for these bookings.

**Comment by CosyStudios** [comment]
Does this fix the fact that property owners receive "guest email notifications" (i.e your stay is 14 days away) for manually created bookings?
