### ISSUE TITLE
Manually created bookings cause admin to receive guest notifications

### ISSUE THREAD

**Issue by CosyStudios** [Roomify/RfA#162]
Possible direct relation of https://github.com/Roomify/RfA/issues/153

When a manual booking is created, the user/author that created it is an administrator/property owner.

As a result, the property owner receives the notification "your booking for * is now only * days away!"

**Comment by CosyStudios** [comment]
Bearing in mind, I have created field_booking_email in the customer profile so that manual bookings can have an email associated with them... 
would something like this work?...
`/**
 * Send 'Booking Reminder' email to guest.
 */
function roomify_accommodation_booking_guest_notification_mail(array $job) {
  if ($booking = bat_booking_load($job['id'])) {
    module_load_include('inc', 'pet', 'pet.rules');

    $booking_wrapper = entity_metadata_wrapper('bat_booking', $booking);

    $to_text = NULL;
    if ($booking->type == 'booking_com') {
      $to_text = $booking_wrapper->field_bcom_email->value();
    }
    elseif ($booking->type == 'roomify_accommodation_booking') {
      $user = user_load($booking->uid);
      if( in_array('roomify_manager', $user->roles) ) {
        // Get the entity ref in booking to guest
        $guest = $booking_wrapper->booking_guest->profile_id->value();
        // load customer profile
        $profile = commerce_customer_profile_load($profile_id);
        if ($profile_wrapper = entity_metadata_wrapper('commerce_customer_profile', $profile)) {
           // set the value of the field and save the profile
           $email_from_customer = $profile_wrapper->field_booking_email->value();
$to_text = $email_from_customer;
        }

      } else {
        $to_text = $user->mail;
      }
      
    }

    if ($to_text !== NULL) {
      $rules_state = new RulesState();

      $rules_state->currentArguments['bat_booking'] = $booking_wrapper;
      $rules_state->variables['bat_booking'] = $booking_wrapper;

      pet_action_send_pet('booking_reminder', $to_text, NULL, NULL, NULL, array(), $rules_state);
    }
  }
}`

**Comment by CosyStudios** [comment]
For clarity, the altered code ...

`elseif ($booking->type == 'roomify_accommodation_booking') {
      $user = user_load($booking->uid);
      if( in_array('nhf_manager', $user->roles) ) {
        // Get the entity ref in booking to guest
        $guest = $booking_wrapper->booking_guest->profile_id->value();
        // load customer profile
        $profile = commerce_customer_profile_load($profile_id);
        if ($profile_wrapper = entity_metadata_wrapper('commerce_customer_profile', $profile)) {
           // set the value of the field and save the profile
           $profile_wrapper->field_booking_email->value();    
        }

      } else {
        $to_text = $user->mail;
      }
      
    }`

**Comment by CosyStudios** [comment]
For clarity, the altered code...

`
elseif ($booking->type == 'roomify_accommodation_booking') {
      $user = user_load($booking->uid);
      if( in_array('nhf_manager', $user->roles) ) {
        // Get the entity ref in booking to guest
        $guest = $booking_wrapper->booking_guest->profile_id->value();
        // load customer profile
        $profile = commerce_customer_profile_load($profile_id);
        if ($profile_wrapper = entity_metadata_wrapper('commerce_customer_profile', $profile)) {
           // set the value of the field and save the profile
           $profile_wrapper->field_booking_email->value();    
        }

      } else {
        $to_text = $user->mail;
      }
      
    }
`

**Comment by CosyStudios** [comment]
Bearing in mind, Ive added field_booking_email to customer profiles so that theres a field to enter in for manual bookings..
Would something like this work?...

`
/**
 * Send 'Booking Reminder' email to guest.
 */
function roomify_accommodation_booking_guest_notification_mail(array $job) {
  if ($booking = bat_booking_load($job['id'])) {
    module_load_include('inc', 'pet', 'pet.rules');

    $booking_wrapper = entity_metadata_wrapper('bat_booking', $booking);

    $to_text = NULL;
    if ($booking->type == 'booking_com') {
      $to_text = $booking_wrapper->field_bcom_email->value();
    }
    elseif ($booking->type == 'roomify_accommodation_booking') {
      $user = user_load($booking->uid);
      if( in_array('roomify_manager', $user->roles) ||  in_array('property_owner', $user->roles)) {
        // Get the entity ref in booking to guest
        $guest = $booking_wrapper->booking_guest->profile_id->value();
        // load customer profile
        $profile = commerce_customer_profile_load($profile_id);
        if ($profile_wrapper = entity_metadata_wrapper('commerce_customer_profile', $profile)) {
           // set the value of the field and save the profile
           $to_text = $profile_wrapper->field_booking_email->value(); 
        }
      } else {
        $to_text = $user->mail;
      }
      
    }

    if ($to_text !== NULL) {
      $rules_state = new RulesState();

      $rules_state->currentArguments['bat_booking'] = $booking_wrapper;
      $rules_state->variables['bat_booking'] = $booking_wrapper;

      pet_action_send_pet('booking_reminder', $to_text, NULL, NULL, NULL, array(), $rules_state);
    }
  }
}
`

**Comment by CosyStudios** [comment]
Ideally, the manual booking still needs to receive notifications as though they booked on the site.

**Comment by salvoscala** [comment]
Hi @CosyStudios, thanks for your report. 
This is an issue we've already planned to work on (https://github.com/Roomify/RfA/projects/2). We're going to reference each booking to a user that can have billing profiles related.

**Comment by CosyStudios** [comment]
Sounds a sensible plan.

Regarding my particular setup (i.e the added field on customer profile) does the above code look roughly correct to you?
Is a bit of a guess at retrieving customer profile fields & am just looking for a temporary solution

**Comment by CosyStudios** [comment]
Is there anyway I can force a call to roomify_accommodation_booking_guest_notification_mail to test this?

Or ideally get kprint_r print out of each variable ive added above so that i can debug myself?

**Comment by salvoscala** [comment]
Hi @CosyStudios your code seems to work well for your use case. I'd only add a control when the booking type is 'roomify_accommodation_booking' to check that a profile referenced exists. I guess you can manually test the function using devel and loading a booking manually.
