### ISSUE TITLE
Chorome XCSRF token issue when altering bookings in availability calendar

### ISSUE THREAD

**Issue by CosyStudios** [Roomify/RfA#163]
In both firefox & safari, a property owner/admin is able to drag/drop bookings around on the calendar and re-assign them to different rooms

Doing this in Chrome results in a permissions error as the CSRF token isnt sent with the BAT API request..

![bat request in chrome](https://cloud.githubusercontent.com/assets/5764179/24608136/1502cfc8-186d-11e7-95bf-67882952a62f.PNG)
![xcsrf fail](https://cloud.githubusercontent.com/assets/5764179/24608135/1500f716-186d-11e7-904c-98fbb0fe57e6.PNG)

**Comment by salvoscala** [comment]
Hi @CosyStudios,
could you manually call ?q=services/session/token and tell us what it returns? thanks!

**Comment by CosyStudios** [comment]
from postman?

**Comment by CosyStudios** [comment]
From postman, I get
vUJiSWpubLscV2ULkNeIjuDrTb7FCR-im64AxxrZguQ (the token)

Directly in the chrome URL, i also get the token
(whilst logged in obv)

**Comment by CosyStudios** [comment]
I thought initally it might be adv_agg or some js bad minification in play
Disabled all adv_agg + caching in dev but got some results.

**Comment by CosyStudios** [comment]
In the inspector above, trying to drag-drop a booking result in the alert to log in - which when passed admin credentials doesnt work either. 
After cancelling the alert, the call to taken looks like this...

![bat_move_network_1](https://cloud.githubusercontent.com/assets/5764179/24611341/b275a2d8-1879-11e7-89d9-75ef8a6e66e0.PNG)
![bat_move_network_2](https://cloud.githubusercontent.com/assets/5764179/24611342/b28dd5ec-1879-11e7-88d3-beaa46ebe33f.PNG)

**Comment by CosyStudios** [comment]
Appears token is received but then the resulting bat operation doesnt seem to include it in the header

![bat_move_network_3](https://cloud.githubusercontent.com/assets/5764179/24611395/db8f5510-1879-11e7-865f-ed6e8c5474b3.PNG)

**Comment by salvoscala** [comment]
I wonder if it could be related to that authentication. Did you try to disable it?

**Comment by CosyStudios** [comment]
disable what?
The alert box?
I've tried both entering my admin credentials yes as well as cancelling the action : Both result in the same output the auth box says "user doesnt have permissions" and the CSRF token as above isnt sent

**Comment by CosyStudios** [comment]
To be clear, its not just on local dev this is happening..
The same on a live roomify site..
http://newhousefarmsussex.com/

**Comment by acrollet** [comment]
Cannot reproduce with chrome, please re-open if this is reproducible with 1.5.0
