### ISSUE TITLE
Deleting a manually enter booking doesnt delete bat event

### ISSUE THREAD

**Issue by CosyStudios** [Roomify/RfA#164]
Deleting a manually created booking )by site admin or property owner) results in the guest being removed from the booking , but the booking still exists in the BAT calendar.

![bat_booking_remove](https://cloud.githubusercontent.com/assets/5764179/24611026/adff0196-1878-11e7-938e-8bf6fed426e3.PNG)
![bat_booking_remove2](https://cloud.githubusercontent.com/assets/5764179/24611025/adfad8aa-1878-11e7-83e9-7c576c5c1024.PNG)

**Comment by CosyStudios** [comment]
Additionally notes, the remainding booking event also spans an extra day (i.e because the 1 minute removd from a bat booking to allow for departure overlap)

This extra day also overwrites any existing booking the following day once the booking relationship is removed!

**Comment by CosyStudios** [comment]
i.e Pre & post screengrab..
Deleting the first booking (15th March) results in the dissaperence of the preceeding booking..
![manual_booking_delete_post](https://cloud.githubusercontent.com/assets/5764179/24612642/c293b124-187d-11e7-8f9f-c6601f763755.PNG)
![manual_booking_delete_pre](https://cloud.githubusercontent.com/assets/5764179/24612641/c292dc72-187d-11e7-91d0-9773b76e6611.PNG)

**Comment by CosyStudios** [comment]
Deleting that "booking" event reveals there is no existing booking underneath

**Comment by acrollet** [comment]
Sorry for the slow reply, please re-open if this issue still exists in 1.5.0
