### ISSUE TITLE
Picking a date range in the bulk pricing update doesnt close the date picker

### ISSUE THREAD

**Issue by CosyStudios** [Roomify/RfA#185]
Screenshot attached for clarity. 

When I pick a start date/ end date for a pricing update via the bulk edit form, the date picker doesnt close and masks the UPDATE button to submit the form
![datepicker](https://cloud.githubusercontent.com/assets/5764179/25432749/9b8c3d3c-2a7d-11e7-9fd0-622f411e3311.PNG)

**Comment by CosyStudios** [comment]
I get multiple errors in the console regarding the Drupal.settings which perhaps are the cause of this.
![console](https://cloud.githubusercontent.com/assets/5764179/25432809/d97e4252-2a7d-11e7-9d69-16f667571c4f.PNG)

**Comment by CosyStudios** [comment]
Additionally, the date format for the form is in international format and this causes confusion with my UK users..
Altering the BAT date format doesnt affect this and should ideally be based on this format like the other forms on the site.

**Comment by CosyStudios** [comment]
As another note to the pricing update form, once a default price has been overidden, there is no method to revert the pricing back to default other than to re-overide the price.

**Comment by CosyStudios** [comment]
Ah.. it seems the console errors relate to jquery validate.
Perhaps this can be disabled for that page?

**Comment by CosyStudios** [comment]
![console2](https://cloud.githubusercontent.com/assets/5764179/25433188/727bcbcc-2a7f-11e7-843c-8b7b5648dadc.PNG)

**Comment by CosyStudios** [comment]
I removed jquery validate from the page and form to clarify but similar errors regarding the .settings property arise & problem persists
![console 3](https://cloud.githubusercontent.com/assets/5764179/25433387/2375be06-2a80-11e7-96b0-475a7b0f0b0a.PNG)

**Comment by CosyStudios** [comment]
Looks like jquery update is loading v.1.10 but this is then being replaced by v 1.7 loaded by adminimal menu
Though it appears adminimal menu takes care of this with 
`
/**
* Use the jQuery no-conflict method so it dosent conflict with drupal's own jQuery.
* This will make the "$" variable to be used by the default Drupal jQuery version 1.4.4,
* And the "$jQueryAdminimal" will be used by the newer jQuery verssion 1.7.2.
*/
var $jQueryAdminimal = jQuery.noConflict(true);
`

Is v1. 10 the correct jquery version to be using?

**Comment by CosyStudios** [comment]
Same problems with jquery updated to 2.1
![console 5](https://cloud.githubusercontent.com/assets/5764179/25433618/e6f8a1c2-2a80-11e7-8c28-9d42c1234347.PNG)

**Comment by CosyStudios** [comment]
Disabled adminimal menu from modules and can confirm the issue persists without it enabled & the second version jquery being loaded.

**Comment by CosyStudios** [comment]
To be clear, I just updated to the latest release and these problems are still persisting

**Comment by nicolocaruso85** [comment]
All errors are related to a module https://www.drupal.org/project/clientside_validation not included in this distro

**Comment by CosyStudios** [comment]
Added 
admin/bat/config/property/manage/3/calendar/pricing
admin/bat/config/property/manage/*/calendar/pricing
to exclude paths in client_validation
and pricing-update-form to 
exclude forms box in config 

But this had no effect

Tried adding pricing-update-form to the "custom forms" config too but no effect

Disabled the clientside validation module entirely and is now resolved.

Shame, that was a really good module for the checkout.

**Comment by CosyStudios** [comment]
Just to update anyone using clientside_validation module, I added roomify_locanda_event_ui_pricing_update_form (the full form name) to the ignore list of forms to validate and this now works
