### ISSUE TITLE
What happened to upcoming bookings?? and bookings in general

### ISSUE THREAD

**Issue by CosyStudios** [Roomify/RfA#186]
I note the admin interface has been updated, but the panel view for upcoming bookings/bookings in general have been removed. 
How does one go about viewing a properties bookings?

I cant see anywhere in the dashboard to access this any longer

**Comment by salvoscala** [comment]
Hi @CosyStudios, we changed something in the dashboard. Did you try to revert features and launch updates?
Thanks!

**Comment by CosyStudios** [comment]
updates applied.
I can see the bookings panel is in the mini panels config for the dashboard but for some reason i cant see 
Ill check the features status - thanks...

**Comment by CosyStudios** [comment]
Reverted "Roomify dashboard" feature but not seeing any effect (after cache flush too) and features still reports as "overridden"
The bookings mini panel appears in the dashboard mini panel content config along with various other new panels that arent being shown. 

I have roomify permissions disabled - Are there any new permissions added that need to be enabled to view? - I presume not because I cant see the bookings tab even as site admin

**Comment by CosyStudios** [comment]
When I inspect the view for "upcoming bookings" - I see my bookings arent showing up - perhaps i cant see the tab because there's no bookings shown.

I note in the filter, there is "Events: State = 4" - if I remove this from the filter, my manual bookings show up and the mini panel successfully shows up in the dashboard now!

"Events: State = 4" is in my existing live site im trying to update and hadnt caused issues before with manual bookings but it appears now this state isnt being saved to manually created bookings.

What does "Events: State = 4" represent and why arent my manual bookings getting this state saved to them?

**Comment by CosyStudios** [comment]
Sorry, to clarify "Events: State = 4" is part of the filter criteria to the view

**Comment by CosyStudios** [comment]
Inspected My test manual booking booking_event_reference and its state is Booked (state_id:5) 

Any idea why the id is different?

in manage/availbility/state , state 4 is "requested" and state 5 is "booked"
where as on my live site which is working - the state for booked is 4 and 5 is "in_conversation"

Where there changes to alter these ID's?
Are these state id's contained in a feature that could be reverted?

**Comment by CosyStudios** [comment]
Odd that my dev store has different state id's to default but none the less works fine on the live site.
