### ISSUE TITLE
Cant run update.php due to RoomifyRateRestriction error

### ISSUE THREAD

**Issue by CosyStudios** [Roomify/RfA#188]
## Current Behavior
Trying to run update.php but I keep getting the error:

Notice: Undefined property: RoomifyRateRestriction::$rate_id in bat_entity_access() (line 166 of /home/nhf/public_html/nhfclean/profiles/roomify/modules/bat/bat/bat.module).

Unsure as to any other information I can provide

**Comment by CosyStudios** [comment]
Oh, just realised..

The update process was aborted prematurely while running update #7008 in entity_translation.module. All errors have been logged. You may need to check the watchdog database table manually.

Poss because entity_translation module is disabled? -> Roomify permissions was dependant on it and I had to disable this to modify permissions to suit needs.

Not sure if RoomifyRateRestriction error is related too but this is a common one that keeps cropping up

Is it possible to disable the updates to the translate module so that update.php can continue and do the update that actually affect me?

**Comment by acrollet** [comment]
@CosyStudios please let us know if this can be reproduced with the default configuration? Unfortunately we can't support every possible customization.

**Comment by CosyStudios** [comment]
Disabled entity_translation module which isnt required since I cant use roomify_translate without enabling roomify_permissions.
Succesfully ran update script

**Comment by acrollet** [comment]
glad to hear it!
