### ISSUE TITLE
No functionality to revert overidden pricing to default

### ISSUE THREAD

**Issue by CosyStudios** [Roomify/RfA#189]
## Current Behavior
Once a default pricing event has been overridden by a new price, theres no method to revert this pricing back to default and it has to be re-overridden 

## Ideal behavior
Provide a reset to default button / option for pricing events

**Comment by CosyStudios** [comment]
Any idea on a timeframe of this?
I realise its marked as an enhancement but my client is finding this behavior very frustrating..
His initial mis-understanding of "default" pricing led him to override an entire years worth of prices and now they cant reflect the default scheme.

Is there a basic SQL statement I can write just to clear one rooms row of overidden prices back to default?

**Comment by acrollet** [comment]
@CosyStudios sorry for the extremely slow reply - no plans to implement this request at this time but we'd be happy to review a pull request or provide a quote for implementation. Please email hello@roomify.us if you're interested in a quote.
