### ISSUE TITLE
I need help for availability constraints start

### ISSUE THREAD

**Issue by lomendy** [Roomify/RfA#193]
Hello, I am looking for help about Roomify for Accommodations self-hosted support package.
I am writing to you because I installed Roomify for Accommodation 1.3.8 but the
restrictions (weekly rentals and Saturday arrivals) do not work.
Can you help me .
Please.
Best regards.
Louis

**Comment by nicolocaruso85** [comment]
more info?

**Comment by lomendy** [comment]
From the unit management interface, when I enter the minimum number of days that can be booked, the constraints are not respected when searching for availabilities.

**Comment by nicolocaruso85** [comment]
Can you provide some screenshots?

**Comment by lomendy** [comment]
![image](https://cloud.githubusercontent.com/assets/18372013/25840473/3a8ba29c-349c-11e7-87fb-fcbf5522484b.png)
Here is the screenshot

**Comment by salvoscala** [comment]
Hi @lomendy,
I've tested availability constraints ( using the ones defined in the screenshot ) and everything seems to work fine to me. If I make a search from the /availability-search that does not respect those constraints, the property doesn't appear. Are there more than one type in the property?
Can you please describe step by step how to reproduce the issue?

Many thanks!

**Comment by lomendy** [comment]
I created a new property, and filled all the fields. In the MANAGE ROOM part I added a ROOM TYPE. I have completed all fields and the BOOKING CONSTRAINTS.
But when I simulate reservations, the search engine shows me all types of rooms regardless of:
_ Minimum Booking Length days
_ Maximum Booking Length is
_ Booking start day

**Comment by nicolocaruso85** [comment]
Sorry but i can't reproduce whit your infos.
In order to help you i need more infos and more screenshots, and all steps.

**Comment by salvoscala** [comment]
@lomendy are you sure that the property has only one room type or, otherwise, each of them has 
the restrictions?
