### ISSUE TITLE
The Roomify Travel theme module should be enabled during the installation

### ISSUE THREAD

**Issue by salvoscala** [Roomify/RfA#2]
It brings panels and views that we need on the travel theme.

**Comment by troffel** [comment]
Roomify for Accommodations 1.2 throws a warning:
User warning: The following module is missing from the file system: module_filter. For information about how to fix this, see the documentation page. in _drupal_trigger_error_with_delayed_logging() (line 1128 of C:\wamp\www\rfa12\includes\bootstrap.inc).
Can I continue with Accommodations 1.2.1? Will this be fixed then

**Comment by acrollet** [comment]
@troffel thanks for the feedback - it's best to keep issues separate so I've created #16 - in the meantime this won't prevent your system from functioning and you can get rid of the message by downloading and installing https://www.drupal.org/project/module_filter
