### ISSUE TITLE
Impossible property translation

### ISSUE THREAD

**Issue by flodaq** [Roomify/RfA#20]
I got a 404 error when trying to translate a property:
The requested page "/en/admin/bat/config/property/manage/31/edit/add/en/fr" could not be found.

I think every required module is installed and enabled as I am able to translate everything else in the website.

**Comment by salvoscala** [comment]
Hi @flodaq, thanks for your feedback! Are you using our latest package version or are you trying to install it with the installation profile?
We patch Drupal Core (https://github.com/Roomify/RfA/blob/master/patches/9to10_menu_max_parts.patch) and increase the MENU_MAX_PARTS variable to avoid that problem.
Hope that can help you.

**Comment by flodaq** [comment]
Hi,
I started with the installation profile and updated several modules with the latest package version.
But you are right, the given patch was not correctly applied. Everything works fine after. My bad. 
Are you going to keep needing a Drupal core patch or is this temporary?

**Comment by salvoscala** [comment]
I think we need that patch for now, at least until it will be integrated on Drupal core ;)
