### ISSUE TITLE
Error when creating new Homepage page

### ISSUE THREAD

**Issue by Elzb** [Roomify/RfA#205]
When trying to save a new homepage content I get the following error:
 Notice: Undefined index: roomify_property in roomify_system_tokens() (line 2158 of /home/.../public_html/.../profiles/roomify/modules/roomify/roomify_system/roomify_system.module).
EntityMalformedException: Missing bundle property on entity of type roomify_property. in entity_extract_ids() (line 7929 of /home/.../public_html/.../includes/common.inc).

**Comment by Elzb** [comment]
Hello, this also happens when editting and trying to save current homepage node.

**Comment by Elzb** [comment]
Nevermind. I think this was something strange on my end

**Comment by Elzb** [comment]
I keep getting this error when trying to create any content.  I thought it went away yesterday.  If you could give me any ideas as to what could this be, that would be greatly appreciated.
Thank you,
Ella

**Comment by acrollet** [comment]
@Elzb could you please follow the new issue template and give us the steps to reproduce the issue, starting with a clean installation? This is what we need to be able to look into this.

thanks!

**Comment by Elzb** [comment]
I think it has to do with adding other modules.  When reverting to last night database all works okay.  I've installed path alias extension module (path_alias_xt) and enabled triggers for action (send email when new account is created).  With clean install all works fine.

**Comment by Elzb** [comment]
Perhaps there is a conflict with path_alias_xt module, all is working fine without it. Closing.
