### ISSUE TITLE
RfA | Travel Theme | Availability Search | Grid View > Problem with number of beds, bathrooms

### ISSUE THREAD

**Issue by acidmind00** [Roomify/RfA#206]
## Expected Behavior
We would expect it to show the exact number of single beds and or double beds followed by the number of the bathrooms for all the property units.

## Current Behavior
After a clean installation of roomify for accomodation version 1.3.8, after inserting a couple of properties, during **availability search** at **'grid'** view the number of beds and bathrooms is always shown as **1**. I believe there has something to do with the indexed fields of N number of beds, bathrooms within Availability Search view. Revert defaults of panel / views doesn't work either.

## Context (Environment)
This should be fixed because guests are getting wrong information regarding number of beds and bathrooms for a house or a room. It should at least be specified to be more accurate.

Please forgive me if there is something i have missed.

**Comment by salvoscala** [comment]
Hi @acidmind00, did you try to change those number from the type page (Manage House tab from the property edit page)? I've tested it and it works fine. See attached screenshots.

Thanks!

<img width="1026" alt="screen shot 2017-05-16 at 10 33 11" src="https://cloud.githubusercontent.com/assets/6781952/26097152/e09ca276-3a23-11e7-90f9-e0f2721bb6ee.png">
<img width="885" alt="screen shot 2017-05-16 at 10 32 33" src="https://cloud.githubusercontent.com/assets/6781952/26097151/e09c7724-3a23-11e7-949d-a25756b66a27.png">
<img width="675" alt="screen shot 2017-05-16 at 10 32 23" src="https://cloud.githubusercontent.com/assets/6781952/26097153/e0e7da0c-3a23-11e7-9b38-7f2e02eb3b66.png">

**Comment by acidmind00** [comment]
You are right. I hadn't filled the entries of beds / bathrooms within room type. I was confussed from the number of beds shown in grid view, with the number of beds shown in list view. I believe it is designed to show the number of beds according to number of max occupancy if no number of beds / bathrooms specified. Isn't it ?

You help is greatly appreciated Salvo. Thank you.

Best Regards

**Comment by salvoscala** [comment]
The grid view shows the total number of capacity in beds (for example 2 single beds + 1 double bed  = 4). The list shows single beds and double beds, in the case you have a multi-room property it will show the biggest one ( with the greatest number of beds ).

Hope this is clear, and it helps! :)

Regards

**Comment by acidmind00** [comment]
It surelly is. 

Thank you.
