### ISSUE TITLE
Taxonomy Area Google Geocode error API key not being passed

### ISSUE THREAD

**Issue by blackdoginet** [Roomify/RfA#231]
## Expected Behavior
enter my API code using the option from Configuration -> Content Authoring -> Geofield GMap and save Then Structure -> Taxonomy -> Area -> Add. In Description tab should be able to enter location for geocoding and marker moves and geo-coordinates found

## Current Behavior
Perform steps above. When go to add area error popup message "Geocoder failed due to: REQUEST_DENIED"
Firebug console message "
Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys"
## Possible Solution
Amend documentation to let users know where to correctly add necesary Google API keys??
## Steps to Reproduce from a clean installation of the latest release
AS above clean install latest release 1.4.1
## Context (Environment)
Debian 8 php7 mariadb server. Browser Firefox ESR

**Comment by blackdoginet** [comment]
FYI Enbled Google API's 
![screenshot from 2017-06-20 10 45 33](https://user-images.githubusercontent.com/17192852/27322208-dfe3790c-55a5-11e7-876a-e6f9192204a1.png)

**Comment by acrollet** [comment]
Sorry for the very slow reply, please re-open if you're still experiencing this issue.

**Comment by acrollet** [comment]
this is fixed in https://github.com/Roomify/RfA/commit/72e1f11dcbb22fba6ead1345414dec767560607e and will be available in the next release.
