### ISSUE TITLE
Error when updating from 1.4.1 to 1.4.2

### ISSUE THREAD

**Issue by Elzb** [Roomify/RfA#244]
Hello,
Trying to update from 1.4.1 to 1.4.2 (before current 1.4.3) release returns the following error:
"The following updates returned messages

roomify_listing module

Update #7038
Failed: FieldException: Attempt to update an instance of a nonexistent field . in field_update_instance() (line 557 of ......./modules/field/field.crud.inc)."
Any tips on what could cause this is greatly appreciated.
Ella

**Comment by acrollet** [comment]
Hi @Elzb,

have you made any modifications to the code? Can you post instructions to reproduce from a clean installation?

thanks so much!

**Comment by Elzb** [comment]
Hello,
No change to code, but will dig deeper, in case I did something and forgot..
Steps taken were to upload all new files per instruction, except of "sites/default/files" folder and run update.php 
I didn't have a problem with any other updates since I started using RfA from version 1.3.8
I will re-upload everything to make sure nothing got skipped along the way.

**Comment by Elzb** [comment]
I can't find what's causing it.  I've updated as per instructions as I've done before, but still have the same error show up.

**Comment by Elzb** [comment]
I found it.  I removed image field (field_st_gallery) sometime ago from type bundle House, and once restored, updates worked.  Thank you for trying to direct me on the right path.

**Comment by acrollet** [comment]
@Elzb no problem, glad you found it!
