### ISSUE TITLE
Unable to add payment gateway modules to packaged version

### ISSUE THREAD

**Issue by gupta** [Roomify/RfA#248]
I downloaded the latest (1.4.3) packaged version of RfA from https://github.com/Roomify/RfA/releases and installed it as per the instructions given.

I am now trying to add other payment modules (tried 3 modules so far) for use with RfA. I am able to add and enable them without any errors. But none of the modules are showing up under "Payment Methods" (http://localhost/mysite/admin/roomify/payment_methods).

There are no errors at http://localhost/mysite/admin/reports/dblog

Modules tried:
Commerce EBS Payment Gateway 7.x-1.1
Commerce PayUMoney 7.x-1.3
Commerce CCAvenue Payment Gateway 7.x-2.0

Environment
Ubuntu 16.04.1
Apache 2.4.18
PHP Version 7.0.18

Can anyone please guide me on how to get the payment modules working?

**Comment by acrollet** [comment]
@gupta we don't show icons for payment modules we don't provide - you'll need to follow the configuration instructions from the module you are installing - we use the drupal commerce checkout, so it should all function as usual once you have your payment gateway configured.

good luck!
