### ISSUE TITLE
dates are no longer available

### ISSUE THREAD

**Issue by gupta** [Roomify/RfA#261]
I am setting up a new RfA site.

When any user searches for room availability, the site consistently display the following below the line  that has Property Name: Room Type Name:

**Error**
These dates are no longer available for "XYZ Hotel - Standard Double Room", please try different dates.
Bookings must start on Monday

Have tried the following:

- made all room-types available until 2020 in "Bulk Availability Update", 
- Set / Reset all booking constraints (such as booking should start on Tuesday)

but still get the same message.

What am I missing? Please help.

Environment
RfA: 1.4.3
Ubuntu 16.04.1
Apache 2.4.18
PHP Version 7.0.18

**Comment by acrollet** [comment]
@gupta thanks for reporting! Could you report the version of RfA, and instructions to reproduce the problem from a clean installation? URLs/screenshots are also very helpful, thanks!

**Comment by acrollet** [comment]
no response.
