### ISSUE TITLE
How to install on acquia dev desktop?

### ISSUE THREAD

**Issue by ugintl** [Roomify/RfA#268]
I downloaded it on 8 Sep 2017. I see there is a .sql file and 2 .patch files. I am little confused. How to import on acquia dev desktop?

Here is I think what I should do:

1. Import local site using acquia dev desktop ui dialogue box.
2. Give a name, url etc
3. Most important. Instead of creating a new database in the dialogue box, import the mysql dump file.

Currently the name of the .sql file is accommodations-database.sql

**Comment by acrollet** [comment]
@ugintl the site in the release package is fully built, so you just need to specify the correct docroot and import the .sql file
