### ISSUE TITLE
Can I edit everything without breaking configuration?

### ISSUE THREAD

**Issue by ugintl** [Roomify/RfA#272]
I want to use this distribution for a different purpose. I want to create a property marketplace with sellers, buyers and agents. Can I do this by deleting existing roles and profiles and creating my own?

It seems to be restricted for a specific purpose. Isn't it? Good if I can modify anything or the whole website without breaking the config.

Any suggestions please?

**Comment by salvoscala** [comment]
Hello @ugintl, as you can see, this distribution has a specific purpose and I would not suggest to make several changes. Anyway, feel free to fork the project and play with that.

Regards
