### ISSUE TITLE
Globally disable bookings with notice

### ISSUE THREAD

**Issue by karudonaldson** [Roomify/RfA#290]
We are testing a small B&B site that it would be useful to have an ability to occasionally shut down all rooms for maintenance or vacations and post a notice on the site stating it's unavailable due to maintenance etc with a resume date displayed.

What is the best way to achieve this if you have a 5 room property?

**Comment by salvoscala** [comment]
Hello @karudonaldson, RfA gives you the ability to disable your properties (from the property edit page) and these won't be visible on you site. Unfortunately, at the moment, you can't disable all properties and show a message.

**Comment by karudonaldson** [comment]
Do you mean the suspend the property option?
I tried suspending the property and it is still available for booking rooms?  Have I missed something there?

**Comment by salvoscala** [comment]
If you suspend a property this won't be listed on the availability search page and the property page itself won't be reachable for normal users. The calendar will remain the same, basically, the users cannot book the property.

**Comment by karudonaldson** [comment]
That's ok, is there a way to keep a property listed, but not allow bookings to any rooms on the property?

**Comment by salvoscala** [comment]
hm, no, I guess you can only update the availability calendar and make it unavailable. Keep in mind that if a user makes a search on dates it won't be shown

**Comment by karudonaldson** [comment]
Ah yes, I can simply set the availability calendar.
