### ISSUE TITLE
Fatal error: Class 'Roomify\Bat\Store\DrupalDBStore' not found in /code/profiles/roomify/modules/bat/bat/modules/bat_event/bat_event.module on line 2401

### ISSUE THREAD

**Issue by karudonaldson** [Roomify/RfA#291]
Setting up a new RFA 1.4.7 site.

I can't reproduce this on my local (latest version of MAMP 4 locally), which has an identical configuration to the two remote servers (Pantheon platform and an Aegir/BOA instance), I found selecting the dates for a booking resulted in this error.

Error: Class 'Roomify\Bat\Store\DrupalDBStore' not found in bat_event_get_calendar() (line 2401 of /code/profiles/roomify/modules/bat/bat/modules/bat_event/bat_event.module).

After selecting a date range, I expect the available rooms to be displayed.

Instead I get:
Error: Class 'Roomify\Bat\Store\DrupalDBStore' not found in bat_event_get_calendar() (line 2401 of /code/profiles/roomify/modules/bat/bat/modules/bat_event/bat_event.module).
The website encountered an unexpected error. Please try again later.

## Steps to Reproduce from a clean installation of the latest release
Select dates arrival and departure hit book now.

## Context (Environment)
RFA Version 1.4.7
Drupal 7.56
NGINX 1.8.1 / PHP5.6 AND PHP 7.0
MariaDB 5.5.5-10.23-MariaDB-log
Any browser

Works fine on local dev under MAMP any sql/php/webserver combo which is really strange?

**Comment by salvoscala** [comment]
Hi @karudonaldson, is the BAT library correctly installed? You can check it at 'admin/config/system/composer-manager' and maybe need to run composer install from the right folder

**Comment by karudonaldson** [comment]
I believe so according to the status page.
What's strange is its working on my local version but when I upload it to another server with identical context, that's when I encounter the issue.

![screen shot 2017-10-30 at 8 50 04 am](https://user-images.githubusercontent.com/444688/32147636-66498e12-bd4f-11e7-8fce-5f51ecfdee5d.png)

**Comment by salvoscala** [comment]
Could you screenshot the page 'admin/config/system/composer-manager' ? thanks!

**Comment by karudonaldson** [comment]
![screen shot 2017-10-30 at 10 45 23 pm](https://user-images.githubusercontent.com/444688/32164425-66ddee34-bdc4-11e7-80a9-4575334a484e.png)

**Comment by salvoscala** [comment]
Could you check that your Vendor directory and the Composer File directory ( from admin/config/system/composer-manager/settings) have the right URL in the server?

**Comment by karudonaldson** [comment]
Found it thanks for that.  The sites/all/vendors/roomify/bat folder was empty.  I SFTP'd it up to the server and everything came alive again thanks heaps for pointing me in the right direction!

**Comment by karudonaldson** [comment]
For anyone testing/developing on Pantheon, the directory
sites/all/vendor/roomify 
Becomes a submodule thus being ignored from being pushed up to the pantheon repo.

I used the following to list
`git submodule--helper list`
then this to  remove the submodule from the pantheon repo so it could be pushed
`git rm --cache sites/all/vendor/roomify/bat`

Hope that helps others.
