### ISSUE TITLE
Disable and remove development modules

### ISSUE THREAD

**Issue by karudonaldson** [Roomify/RfA#295]
Just curious to know, at install time it's offered to install development tools.

If a site is finished being developed, what steps are recommended to remove the development toolset from the system?

**Comment by salvoscala** [comment]
Hello @karudonaldson, the dev options offered during installation enables some modules:
 - views_ui,
 - rules_admin
 - slick_ui
 - devel
 - diff
 - module_filter

You might disable these modules if you don't need them.
Regards
