### ISSUE TITLE
FullCalendar Library could not be found

### ISSUE THREAD

**Issue by BMriesh** [Roomify/RfA#306]
When I bought the themes (Booking+), all the immigrants worked freely, unfortunately I had to reinstall the homepage completely, after the new installation, some things did not work properly, among others is the error that the FullCalendar no longer find and it also does not work correctly.
Please find attached screenshots for this problem. 
Please help me solve this problem.

Best regards
Basem

![screenshot](https://user-images.githubusercontent.com/33370235/32978707-f9d8fb20-cc47-11e7-833f-6649b01e1e88.png)
![screenshot-error message](https://user-images.githubusercontent.com/33370235/32978708-fa034614-cc47-11e7-9c78-75496d11a2a2.png)
![screenshot-license key](https://user-images.githubusercontent.com/33370235/32978709-fa2236f0-cc47-11e7-8262-3446b23b9fc6.png)
![screenshot-modules](https://user-images.githubusercontent.com/33370235/32978710-fa3e6ff0-cc47-11e7-8594-6783a3386acc.png)
![screenshot-modules-bat](https://user-images.githubusercontent.com/33370235/32978711-fa5f4d42-cc47-11e7-8a8e-46ca163458de.png)
![screenshot-modules-bat2](https://user-images.githubusercontent.com/33370235/32978712-fa844f5c-cc47-11e7-8f1b-fedd9cc1f1cb.png)
![screenshot-modules-bat3](https://user-images.githubusercontent.com/33370235/32978713-faaacec0-cc47-11e7-89ac-c0bf88aeba86.png)

**Comment by nicolocaruso85** [comment]
The theme "Booking+" cannot work with Rfa

**Comment by acrollet** [comment]
We do not provide the Booking+ theme, please contact the authors for support.
