### ISSUE TITLE
Composer´s update command warning/failure when installing/updating roomify

### ISSUE THREAD

**Issue by VillaCare** [Roomify/RfA#321]
## Expected Behavior

A clear update / install of roomify

## Current Behavior

It started updating but when installing the warning " Pls inform on solution on this warning "Composer´s update command must be run to install required packages " came up leaving a uninstalled programm
## Possible Solution

Have no idea, is there a file missing?

## Steps to Reproduce from a clean installation of the latest release

New DB, new download of github.com/Roomify/RfA/releases/tag/1.4.8
than install and after 1st install warning appears 

1.<img width="397" alt="screen shot 2017-11-26 at 17 34 17" src="https://user-images.githubusercontent.com/25827314/33337516-72e759d4-d473-11e7-8035-7a285a227107.png">

2.<img width="2048" alt="screen shot 2017-11-28 at 19 38 12" src="https://user-images.githubusercontent.com/25827314/33337602-bb27123e-d473-11e7-8bed-6ff4fbb4d41d.png">3.
4.

## Context (Environment)

Not knowing what to do thought of making the page new again.

Safari

**Comment by VillaCare** [comment]
Made a new install with the latest version and the moment it starts installing additional functionality the warning shows up

<img width="2048" alt="screen shot 2017-11-29 at 19 21 26" src="https://user-images.githubusercontent.com/25827314/33391901-c476990a-d53a-11e7-8b48-c8cdb1872b07.png">

**Comment by VillaCare** [comment]
Issue was not resolved

**Comment by acrollet** [comment]
@VillaCare is your concern about the warning, or is something not working in your installation? If it's about the warning, the update command is run later in the installation process, there's not anything we can do about it. Feel free to re-open if there's something not working.

**Comment by VillaCare** [comment]
Hi, after a complete new install of roomify received the following note
<img width="2048" alt="screen shot 2017-12-10 at 08 25 17" src="https://user-images.githubusercontent.com/25827314/33803022-7053026a-dd86-11e7-8ad5-22437419682f.png">

Leaving this as result,

<img width="891" alt="screen shot 2017-12-10 at 08 46 55" src="https://user-images.githubusercontent.com/25827314/33803051-f606c090-dd86-11e7-880e-2bb3f736dc95.png">

Pls advise, rgds
