### ISSUE TITLE
Access api for search, booking, creating property

### ISSUE THREAD

**Issue by niranjanatseken** [Roomify/RfA#324]
## Steps to Reproduce from a clean installation of the latest release

1.
2.
3.
4.

**Comment by niranjanatseken** [comment]
I want to know the request parameters for search, booking and creating property in BAT API.

**Comment by acrollet** [comment]
@niranjanatseken there are unfortunately no API docs - there is no API for search or creating a property, but you can look at the docs for https://www.drupal.org/project/services and see how we've used the services module with bat_api. For bookings, you can use your browser to inspect the calls when adding a booking on the property calendar. We'd love any contributions you could make for docs or increased API capability.
