### ISSUE TITLE
Safari + OS X default theme has layout problems

### ISSUE THREAD

**Issue by karudonaldson** [Roomify/RfA#327]
Hi guys,

Latest Roomify 1.8.4
Mac OS High Sierra 10.13.1
Safari Version 11.0.1 (13604.3.5)

1.  The room search boxes are off the screen and are sitting too low on the landing page meaning you have to scroll down to view them.  UX issue
2.  Below the home page slider shows a big area of white space in the default theme.
Chrome and Firefox displays fine.  Looks like it's missing a block

Hope that helps

**Comment by salvoscala** [comment]
Hello @karudonaldson, could you provide some screenshots?

Thanks!

**Comment by karudonaldson** [comment]
Um, I feel a bit a bit embarrassed now, the issues don't exist after more testing this evening!  Very strange but good :)

**Comment by bulletproofsamples** [comment]
Karu, Sorry to reach out to you this way, but haven't been able to find your information anywhere else. Alex from Bulletproof samples gave me your name. we are the new owners and need to talk with you about the web site.
i can be reached at dale@bulletproofsamples.com
