### ISSUE TITLE
Composer update command / installation issue

### ISSUE THREAD

**Issue by VillaCare** [Roomify/RfA#336]
Composer update command issue
## Expected Behavior

A normal functional install of Roomity with install of required modules etc.

## Current Behavior

Note comes up during install;
<img width="2048" alt="screen shot 2017-12-10 at 08 25 17" src="https://user-images.githubusercontent.com/25827314/33803260-e4b14bbc-dd8b-11e7-8e60-49e50d3e116b.png">

## Steps to Reproduce from a clean installation of the latest release

During a clean/new installation of Roomify and changing registration details the install continues then the note to run Composer update pops up and leaves see screenshot 2

1.
<img width="2048" alt="screen shot 2017-12-10 at 08 25 17" src="https://user-images.githubusercontent.com/25827314/33803278-761ffed6-dd8c-11e7-86fc-7dac4e17b4b8.png">

2.
<img width="891" alt="screen shot 2017-12-10 at 08 46 55" src="https://user-images.githubusercontent.com/25827314/33803280-793c3b52-dd8c-11e7-9bbd-0d8c5a196b8e.png">

3.
4.

## Context (Environment)

A not working page / Just to have a paid site running/working

IOS / Safari

**Comment by acrollet** [comment]
Hi there,

can you post the complete steps of how you are installing the site? The 'composer update' warning is normal and not symptomatic on its own.

**Comment by VillaCare** [comment]
Hi, 

1st I download te new update, than I backup the old version as mentioned and after this is done I upload the new version to the 1and1 hosting server, once done I follow the procedures by uploading the sites files and continue by using the update function in the application. This goes well until it asks info on user which I change/personalize, than it starts the installation and pops up the composer note. When install completed to return to the web page it ends up as the before mentioned 2nd screenshot.
rgds

**Comment by acrollet** [comment]
@VillaCare if you are updating an existing installation, you should be on update.php rather than install.php - please exactly follow the instructions at http://docs.roomify.us/accommodations_selfhost/index.html#updating and report back.

**Comment by VillaCare** [comment]
Hi, yes that is what I normally do but this last time it was a clean new install giving me this pop up and result. All was new, new DB, fresh download, and install. (was not a update!)

**Comment by acrollet** [comment]
does the update give the same result? or a different one?

**Comment by VillaCare** [comment]
The reason for a complete new install was the result from a update

**Comment by VillaCare** [comment]
At the moment I am deleting all for a new install

**Comment by acrollet** [comment]
If you're doing a clean installation, I would suggest using the provided database dump in the release files.

**Comment by VillaCare** [comment]
Just wondering but could IOS/Safari causing the issue?

**Comment by acrollet** [comment]
This is not likely to be a browser-related issue, please try using the DB dump. thanks!

**Comment by VillaCare** [comment]
Once done I let you know

**Comment by VillaCare** [comment]
Complete new install, followed the instructions, only by opening the link/page I have this 

<img width="2048" alt="screen shot 2017-12-11 at 20 46 28" src="https://user-images.githubusercontent.com/25827314/33850554-80dcad1e-deb4-11e7-8158-26db7310d036.png">

No install, no update just this screen ???

**Comment by VillaCare** [comment]
Good morning, 
over night I deleted all again, created a new database, downloaded the https://github.com/Roomify/RfA/releases/download/1.5.0/roomify-accommodations-default.1.5.0.zip files new, separated the sql file as mentioned in the manual for separate upload. This morning fresh install, all seemed to go well:

1; 
<img width="2048" alt="screen shot 2017-12-12 at 07 38 34" src="https://user-images.githubusercontent.com/25827314/33870967-be3354c2-df10-11e7-9299-adc76374177a.png">

2; 
<img width="2048" alt="screen shot 2017-12-12 at 07 38 52" src="https://user-images.githubusercontent.com/25827314/33870996-d62e8aa6-df10-11e7-828c-14a9aed7f25c.png">

3; up to here all looked fine
<img width="2048" alt="screen shot 2017-12-12 at 07 42 37" src="https://user-images.githubusercontent.com/25827314/33871011-ec88d5cc-df10-11e7-9f7b-a41d9e815c9c.png">


4; than the disappointing result!!
<img width="2048" alt="screen shot 2017-12-12 at 07 44 43" src="https://user-images.githubusercontent.com/25827314/33871039-fd6eb0d2-df10-11e7-8e39-f60b10fbc85b.png">


Really do not know what to do,

Rgds,

**Comment by acrollet** [comment]
Hi there,

please try importing the included .sql file to your database - you won't need to run the Drupal installation script that way.

**Comment by VillaCare** [comment]
Even when that was used for the main install?

Verstuurd vanaf mijn iPhone

**Comment by acrollet** [comment]
I'm sorry, but I'm not sure what you're trying to accomplish right now - if you're trying to update an existing installation, you should update the code base and run update.php. If you're trying to make a new installation, you should import the .sql file to your database.

**Comment by VillaCare** [comment]
Hi, What I try to accomplish is to have it working as it should.

There is something that „blocks“ the site. When I make a clean install according your description it unpacks the data. I import the sql file into the new DB as described and perform the installation following you’re steps.

Reason to make a new install was that when doing an update to the latest version I ended up with this,



I tried to set it all back using a back up without result.

So than I decided to make a clean new install but what ever I do following even your latest instructions I end up with the same panel (see screen shot) 

PLs advise


Ferdinand van Reijsen
VillaCare
HTTP://www.villacare.eu

**Comment by salvoscala** [comment]
Hi @VillaCare, I've tried to reproduce your issue without luck.
I've downloaded the latest release, installed on a new DB and it works fine. I've also tried the bumped DB and it doesn't have any issue.
Did you check that paths at 'admin/config/media/file-system' are set fine?

**Comment by VillaCare** [comment]
I really to not understand, once again made a new install but I finish every time with the same result. I tried to find the mentioned file but cannot find it to check.

I send a status report maybe you see something that clears something 


Info | Drupal | 7.56
-- | -- | --
Info | Install profile | Roomify (roomify-)
OK | Access to update.php | Protected
OK | Adv CSS/JS Agg | OK
Advanced CSS/JS Aggregator should be working correctly.
Warning | AdvAgg Compress CSS | The YUI-CSS-compressor-PHP-port library needs to be updated.
Go to the YUI CSS compressor PHP port page and download the latest version (4.1.0) into the libraries folder (usually sites/all/libraries). An example valid filename is sites/all/libraries/YUI-CSS-compressor-PHP-port/README.md.
Warning | AdvAgg Modifier | The loadCSS library needs to be updated.
Go to the loadCSS page and download the latest version (2.0.1) into the libraries folder (usually sites/all/libraries). An example valid filename is sites/all/libraries/loadCSS/package.json.
OK | BAT jQuery Requirements | 1.10
OK | BAT PHP Library | BAT PHP Library installed
OK | Composer Manager | Dependencies installed
Visit the package status page to view the status of individual packages.
OK | Configuration file | Protected
OK | Cron maintenance tasks | Last run 1 min 32 sec ago
You can run cron manually.To run cron from outside the site, go to http://s568653887.mialojamiento.es/cron.php?cron_key=n-E3X27ONfMiWaRRqiEyzMW6uTF_DLk-Wi63iPKQiX8
OK | CTools CSS Cache | Exists
OK | cURL | Enabled
Info | Database 4 byte UTF-8 support | Disabled
4 byte UTF-8 for mysql is disabled. See the documentation on adding 4 byte UTF-8 support for more information.
OK | Database system | MySQL, MariaDB, or equivalent
OK | Database system version | 5.5.57-0+deb7u1-log
OK | Database updates | Up to date
OK | Date API | System date settings
The timezone has been set to Europe/Madrid. The medium date format type has been set to Sat, 12/16/2017 - 13:33. You may find it helpful to add new format types like Date, Time, Month, or Year, with appropriate formats, at Date and time settings.
OK | Drupal core update status | Up to date
OK | File system | Writable (public download method)
OK | FooTable |  
OK | FullCalendar | FullCalendar, Scheduler and Moment Installed
The FullCalendar, FullCalendar Scheduler and the Moment Library are installed
OK | GD library PNG support | bundled (2.1.0 compatible)
OK | GD library rotate and desaturate effects | bundled (2.1.0 compatible)
Info | GeoPHP and GEOS | GeoPHP library installed and OK. However, GEOS is was not found. While not required, you will see performance improvements if you install the GEOS PHP extension. See the following link for more information.https://github.com/phayes/geoPHP/wiki/GEOS
OK | GeoPHP Library Installed | GeoPHP 1.1 library installed at profiles/roomify/modules/contrib/geophp/geoPHP/geoPHP.inc
OK | imagesLoaded | 2.1.2
OK | imgAreaSelect | 0.9.11-rc.1
Error | Integration with Google reCAPTCHA service! | Not defined!
Google reCAPTCHA: You must to define public and secret keys to protect Your site from spam. You can do it here >>. Better not to put it off on the later time - spammers are not asleep. Let's make their life harder!! :))
OK | jQuery Images Loaded | 4.1
OK | jQuery Masonry | 4.1.1
OK | jQuery Update | jQuery 1.10.2 (configure) and jQuery UI 1.10.2
OK | Leaflet | 1.0.3+ed36a04
The Leaflet Javascript library is installed correctly. 22 maps available.
Info | Metatag | The Imagecache Token module is recommended.
It is recommended to install the Imagecache Token module to make it easier to control image meta tags, e.g. og:image. See the Metatag module's README.txt for details.
Info | Metatag | The Transliteration module is recommended.
It is recommended to install the Transliteration module to clean up filenames of uploaded files that may be used with image meta tags.
Error | Module and theme update status | Not secure!
There are security updates available for one or more of your modules or themes. To ensure the security of your server, you should update immediately! See the available updates page for more information and to install your missing updates.
Warning | MySQL - max allowed packet | 10 MB
Your MySQL 'max_allowed_packet' setting may be too low for Views data export to function correctly, Drupal's requirements recommend setting it to at least 16M. See: http://drupal.org/requirements
OK | Node Access Permissions | Disabled
If the site is experiencing problems with permissions to content, you may have to rebuild the permissions cache. Rebuilding will remove all privileges to content and replace them with permissions based on the current modules and settings. Rebuilding may take some time if there is a lot of content or complex permission settings. After rebuilding has completed, content will automatically use the new permissions. Rebuild permissions
OK | Panels uuid support. | Available
OK | PHP | 7.0.26 (more information)
OK | PHP extensions | Enabled
OK | PHP memory limit | 256M
OK | PHP register globals | Disabled
OK | RRSSB library | 1.8.1
OK | Selct2 plugin | 4.0.3
OK | Services Authentication Mechanism | Enabled for all Endpoints
Warning | Spyc | The Spyc library could not be found.
OK | Stripe currency check | Valid currency
OK | Stripe PHP library | Installed
OK | Unicode library | PHP Mbstring Extension
OK | Update notifications | Enabled
Info | Upload progress | Not enabled
Your server is capable of displaying file upload progress, but does not have the required libraries. It is recommended to install the PECL uploadprogress library (preferred) or to install APC.
Error | Video transcoder: FFmpeg / avconv |  
Missing the transcoder library. Please install FFmpeg in to your server if you intend to transcode or to auto create thumbnails.
OK | Views Data Export temporary directory | Exists
OK | Web server | Apache
OK | XML sitemap | Last attempted generation on Sat, 12/16/2017 - 13:31 (1 min 32 sec ago).
OK | XML sitemap cache directory | Writable

**Comment by salvoscala** [comment]
@VillaCare you have to check paths of your file system at "admin/config/media/file-system" are set fine and try to re-submit that form or make sure that those folders exist.

Regards

**Comment by VillaCare** [comment]
Ill checked see screenshot

<img width="1059" alt="screen shot 2017-12-18 at 20 09 36" src="https://user-images.githubusercontent.com/25827314/34123323-6dc3822c-e42f-11e7-902a-045a9fc3ee3b.png">

Mentioned folders are there

**Comment by VillaCare** [comment]
Can it be a setting in the htaccess file?

**Comment by salvoscala** [comment]
I don't think so - Anyway we can't reproduce your issue. I've tried to install the latest release (https://github.com/Roomify/RfA/releases/tag/1.5.0) and everything works fine.

I think that the problem is related to the files folder. You should check that those are created and accessible on your server

**Comment by VillaCare** [comment]
Ill check with provider but at time they are not really helpful as they mention it to be a developer issue.
I really do not understand, until a few releases ago all was fine, one update and all got messed up. Have done now several new installs without succes

**Comment by VillaCare** [comment]
Good afternoon, Spoke with 1and1 this morning, they claim all is fine on their side.

This afternoon I deleted once again the DB and all roomify data on their server. Downloaded the files from your link above, created a new DB, uploaded the data on to the 1and1 server following the steps mentioned in your manual, result: 

<img width="2048" alt="screen shot 2017-12-19 at 16 10 36" src="https://user-images.githubusercontent.com/25827314/34163519-35122674-e4d7-11e7-9fba-a398e2492a08.png">

Is it an option that I send you log in data and that you do the install to see if that gives the same result?

**Comment by VillaCare** [comment]
In the mean time and a few installs later, even from different PC, and although 1and1 tried to help sorting it out, still no result or install

**Comment by VillaCare** [comment]
Hi,
I wend back a couple of releases and that functioned, then I update release by release untill the last and it still seems OK. 

Now I have the following: 

<img width="561" alt="screen shot 2017-12-24 at 17 52 19" src="https://user-images.githubusercontent.com/25827314/34359537-1ea8584a-ea59-11e7-9eba-c8c03f06bb61.png">

Rgds,

**Comment by VillaCare** [comment]
Hi, I have tried to install over and over again, various ways, changed more than once PC, talked to 1and1 the host but keep having the same result. Hope you understand that after paying USD 250,00 for a program that does not seem to work that I end up very disappointed. What can be done to get it working on 1and1? Pls let me know what costs would be involved to have it installed or what other options you can propose.
It has been working for a while but after a update all got messed up

**Comment by salvoscala** [comment]
Hi @VillaCare, did you try to use a previous release of RfA?

**Comment by VillaCare** [comment]
Yes, had it working but with a new release it messed up.

**Comment by VillaCare** [comment]
Hi, just have been on the phone for an hour with a tech from 1and1 who deleted all files and DB and made a new install freshly downloaded from your GitHub site, following the instructions. He has the same result as if something is missing leaving like a empty page / no content

**Comment by salvoscala** [comment]
@VillaCare Can you please email me at salvo@roomify.us?
