### ISSUE TITLE
Calendar widget does not work on mobile devices

### ISSUE THREAD

**Issue by nbogatov** [Roomify/RfA#341]
The date field widget does not work on mobile devices. It should be like this:
https://yadi.sk/i/I3i1BO203QpWt6
And works like this:
https://yadi.sk/i/xjEto2an3QpWuy

Example: http://domvbo.ru/

**Comment by nicolocaruso85** [comment]
Already fixed in the last version of Rfa 1.5.0

**Comment by acrollet** [comment]
please update to 1.5.0 and re-open if the issue re-occurs.
