### ISSUE TITLE
Losing Roles and Permissions after cron run

### ISSUE THREAD

**Issue by ivanatrix** [Roomify/RfA#352]
I am facing a pressing problem with my new installation of RfA. When I create new roles, or set any type of permissions it saves it, but after running cron or flushing cache these roles and permissions disappear. Anyone ever experienced the same thing

I'm using the entire Roomify for Accommodations package, I have no other modules installed outside of it.

**Comment by acrollet** [comment]
Please see http://docs.roomify.us/accommodations_selfhost/index.html#customizing-roomify-for-accommodations, item 4. best of luck!
