### ISSUE TITLE
Project.make file doesn't recurse drupal-org.make

### ISSUE THREAD

**Issue by serhatozkara** [Roomify/RfA#353]
When building Roomify with project.make file,  destination results in empty roomify profile directory
## Expected Behavior
Upon building,project.make file recurse drupal-org.make and build contrib modules, libraries etc. accordingly with populated roomify profile directory

## Current Behavior
Drush make ends with emty profiles/roomify directory

## Possible Solution
Changing line # 14 of project.make from `file:///tmp/roomify.tar.gz` to `/tmp/roomify.tar.gz` seems to correct the issue

## Steps to Reproduce from a clean installation of the latest release
git clone https://github.com/Roomify/RfA.git
cd RfA
drush make project.make somedirectory/

**Comment by acrollet** [comment]
@serhatozkara what version of drush are you using? thanks!

**Comment by serhatozkara** [comment]
@acrollet I'm on 8.1.3, thanks

**Comment by acrollet** [comment]
@serhatozkara just to be clear, are you following the procedure in https://github.com/Roomify/RfA/blob/master/INSTALL.md and creating the archive? thanks

**Comment by serhatozkara** [comment]
Yes, I'm following the procedure but i have to use pressflow core instead of standart drupal core, so, I'm patching .make file to use pantheon drops as core:

```
--- drupal-org-core.make	2018-01-21 20:06:48.000000000 +0300
+++ drupal-org-core.make	2018-01-21 18:42:37.000000000 +0300
@@ -1,9 +1,11 @@
 api = 2
 core = 7.x
-projects[drupal][version] = 7.56
+projects[pressflow][type] = "core"
+projects[pressflow][download][type] = "git"
+projects[pressflow][download][url] = "git://github.com/pantheon-systems/drops-7.git"
 
 ; Patches for Core
-projects[drupal][patch][] = "http://drupal.org/files/issues/install-redirect-on-empty-database-728702-36.patch"
-projects[drupal][patch][] = "http://drupal.org/files/1275902-15-entity_uri_callback-D7.patch"
-projects[drupal][patch][] = "patches/9to10_menu_max_parts.patch"
-projects[drupal][patch][] = "patches/robots_txt.patch"
+projects[pressflow][patch][] = "http://drupal.org/files/issues/install-redirect-on-empty-database-728702-36.patch"
+projects[pressflow][patch][] = "http://drupal.org/files/1275902-15-entity_uri_callback-D7.patch"
+projects[pressflow][patch][] = "patches/9to10_menu_max_parts.patch"
+projects[pressflow][patch][] = "patches/robots_txt.patch"
```

But the same problem occurs with unmodified core and makefile from RfA

**Comment by serhatozkara** [comment]
This is the bash script that i'm using to update RfA:
```
#!/bin/bash
latest_tag=$(curl https://api.github.com/repos/roomify/rfa/releases/latest -s | jq .tag_name -r)
echo Latest Release is: $latest_tag
git clone https://github.com/Roomify/RfA.git -b $latest_tag
cd RfA
pwd
echo Gzipping Roomify into /tmp...
git archive HEAD | gzip > /tmp/roomify.tar.gz
echo Patching drupal.org makefile to use Pantheon DROPS core...
patch -p0 < ~/Documents/pressflowcore.patch
echo Patching Project makefile for tmpfile location...
patch -p0 < ~/Documents/project_makefile.patch
echo Starting Drush Make...
drush make project.make ../Roomify-"$latest_tag"/ --overwrite
cd ../Roomify-"$latest_tag"/
rm -rf Sites/
cd ..
read -p "Do you want to remove RfA directory?[y/n] " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    rm -rf RfA
fi
echo Removing temp files...
rm /tmp/roomify.tar.gz
echo DONE! ENJOY your ☕️
```

**Comment by acrollet** [comment]
@serhatozkara according to http://docs.drush.org/en/8.x/make/#project-download-options, drush make should accept either a bare path or the file:// protocol. Given that file:// should be OS-independent, it's theoretically superior. Can you reproduce the issue on your system with a minimal makefile?

**Comment by serhatozkara** [comment]
OK, i will check again with stock RfA and report back the behaviour.

**Comment by serhatozkara** [comment]
Strange, as i don't have this problem anymore either with original makefile or the one i patched. This might be a permissions problem on my part. I'm closing this issue now.
