### ISSUE TITLE
Token not working in email templates

### ISSUE THREAD

**Issue by blackbart420** [Roomify/RfA#355]
Hello,

in the "New order" email template, the token [bat_booking:booking-telephone] for customer telephone does not seem to work

**Comment by acrollet** [comment]
@blackbart420 could you confirm which version of RfA you're using?

**Comment by blackbart420** [comment]
I think it is 1.3.1

**Comment by acrollet** [comment]
ok @blackbart420 please re-open this issue if it's reproducible with 1.5.1. thanks!
