### ISSUE TITLE
translation of the interface

### ISSUE THREAD

**Issue by KanOspan** [Roomify/RfA#359]
Hi,
I use Roomify-accommodations 1.4.8
![-1](https://user-images.githubusercontent.com/36164054/35812896-639afc2c-0abc-11e8-8dac-6d37c4158561.PNG)

Tell me please.
I can not find a template file to translate these words. The standard translation function does not work.
How can I do that?

**Comment by nicolocaruso85** [comment]
Go to admin/config/regional/translate/translate and search for "Search Availability"

**Comment by KanOspan** [comment]
I already did it, this does not work

**Comment by nicolocaruso85** [comment]
Go to "admin/config/regional/translate/i18n_string", select "Panels" and click on "Refresh strings"

**Comment by KanOspan** [comment]
Thanks, nicolocaruso85!
but why is only the English version displayed?  
I need a Russian version.
What do you think?

![default](https://user-images.githubusercontent.com/36164054/35898165-0f4c9f16-0bef-11e8-8619-1aa5b4d9a460.PNG)

**Comment by acrollet** [comment]
@KanOspan you translated both lines into russian? Can you upload a screenshot of the translation page as well?

**Comment by KanOspan** [comment]
Hi, acrollet
Did I understand you correctly.
Like this.
![default](https://user-images.githubusercontent.com/36164054/36011424-40bbf0f4-0d81-11e8-9601-4b8eb8efc42c.PNG)

English version
![en](https://user-images.githubusercontent.com/36164054/36011548-52944f8c-0d82-11e8-95ee-4bb93a0e809c.PNG)

**Comment by KanOspan** [comment]
thank you all, I solved the problem
