### ISSUE TITLE
Permissions for different roles are not saved

### ISSUE THREAD

**Issue by nbogatov** [Roomify/RfA#362]
How to fix?

**Comment by nicolocaruso85** [comment]
Please see http://docs.roomify.us/accommodations_selfhost/index.html#customizing-roomify-for-accommodations, item 4. best of luck!

**Comment by salvoscala** [comment]
Hi @orgkolyuchyorg, permissions are exported in code so they will be overridden every time you clean the site's cache.
You should look at the roomify_rights module and implement a hook to add permissions that you need.
Regards

**Comment by nbogatov** [comment]
Disabling the module helped.
