### ISSUE TITLE
Add blocks to the panel

### ISSUE THREAD

**Issue by nbogatov** [Roomify/RfA#366]
After changing the "availability-search" panel, the "availability-search" no opens. 
Q: How do I add my blocks to the panel?

**Comment by salvoscala** [comment]
Hi @orgkolyuchyorg , what kind of block did you add?

**Comment by nbogatov** [comment]
I want to add a news block or some own block

**Comment by salvoscala** [comment]
Did you check if there are some visibility rules in the panel?
You should be able to add blocks

**Comment by nbogatov** [comment]
What happens when I add a block
https://yadi.sk/i/F6O5mADC3SThev

http://2018.domvbo.ru/availability-search

**Comment by nicolocaruso85** [comment]
Fixed here https://github.com/Roomify/RfA/commit/6c4bfcf5b872629d2251800590ccdf16b1df3f5a
