### ISSUE TITLE
RfA

### ISSUE THREAD

**Issue by Sebastien-Spencer** [Roomify/RfA#384]
Error | Unresolved dependency | Corresponding Entity References (Version >=3.x required)
-- | -- | --
Roomify Accommodation Booking requires this module and version. Currently using Corresponding Entity References version
Error | Unresolved dependency | Corresponding Entity References (Version >=3.x required)
Roomify Conversations requires this module and version. Currently using Corresponding Entity References version

## Expected Behavior

just testing this version on a local host and get the above warnings when trying to run update php

## Steps to Reproduce from a clean installation of the latest release

1.
2.
3.
4.

**Comment by acrollet** [comment]
@Sebastien-Spencer this is a difficulty with the fact that CER hasn't had a new release in some time, and we have to depend on the dev version. (which update.module doesn't understand well)

**Comment by acrollet** [comment]
@Sebastien-Spencer this is fixed with https://github.com/Roomify/RfA/commit/4f38b6ea99f37fb1d6b4ca01a429f858e134222b

thanks for reporting!

**Comment by acrollet** [comment]
This fix has been released in 1.5.4
