### ISSUE TITLE
Drush problem in 1.5.3

### ISSUE THREAD

**Issue by vitamate** [Roomify/RfA#386]
Using Drush it seems that the API for core EntityAPIControllerExportable and EntityAPIController classes does not comply. 

## Expected Behavior
Able to run drush

## Current Behavior
Unable to run drush

## Possible Solution
[fix_drush-EntityAPIController.txt](https://github.com/Roomify/RfA/files/2019279/fix_drush-EntityAPIController.txt)

## Steps to Reproduce from a clean installation of the latest release

1.
2.
3.
4.

**Comment by TBK** [comment]
Mostly fixed with https://github.com/Roomify/bat_drupal/commit/3057bc25f877adc5c81628bc1e2dc1bb8632f34a

The following change is still needed for https://github.com/Roomify/roomify_property/blob/master/roomify_property.module
```
--- a/profiles/roomify/modules/roomify/roomify_property/roomify_property.module
+++ b/profiles/roomify/modules/roomify/roomify_property/roomify_property.module
@@ -478,7 +478,7 @@
   /**
    * {@inheritdoc}
    */
-  public function save($entity) {
+  public function save($entity, DatabaseTransaction $transaction = NULL) {
     global $user;
 
     $entity->revision_uid = $user->uid;
@@ -507,7 +507,7 @@
   /**
    * {@inheritdoc}
    */
-  public function delete($ids) {
+  public function delete($ids, DatabaseTransaction $transaction = NULL) {
     foreach (roomify_property_load_multiple($ids) as $property) {
       $uri = $property->uri();
```
