### ISSUE TITLE
Great distribution but I am confused

### ISSUE THREAD

**Issue by ugintl** [Roomify/RfA#407]
![listing-page](https://user-images.githubusercontent.com/12570802/60361721-63fd6200-99f8-11e9-866a-b74935439255.png)
![roomtype1](https://user-images.githubusercontent.com/12570802/60361723-63fd6200-99f8-11e9-9ce3-e5b9517e57c2.png)

I have attached 2 images. 1. From the listing/casa-sul-mare page     2. From room-type/1 page.

These are pages for same property. My question is that why there are 2 separate pages? Amenities are displayed on one page, but not displayed on other page. Logically speaking, there should only be 1 page for 1 property. Please explain.

**Comment by acrollet** [comment]
Hi there,

this is because of the architecture that allows for properties having multiple room types. Since this is a vacation rental, the property only has one room type,  which is the whole house. Amenities are displayed on the room type page since they might vary between room types.
