### ISSUE TITLE
Access denied for admins

### ISSUE THREAD

**Issue by ugintl** [Roomify/RfA#408]
I see access denied errors on few pages as admin. I do not understand why. For example admin/bat/config/booking/add/roomify_accommodation_booking

**Comment by acrollet** [comment]
as user 1, or the roomify manager role?

**Comment by ugintl** [comment]
as user 1

**Comment by acrollet** [comment]
@ugintl I can reproduce the issue - can you post the other paths you've had trouble accessing?

**Comment by ugintl** [comment]
admin/config/workflow/entity_rules

When clicking on administer rules

**Comment by nicolocaruso85** [comment]
@ugintl
for "entity rules" you can change settings here "admin/config/workflow/entity_rules/settings" see function entity_rules_overview_access()

Path "admin/bat/config/booking/add/roomify_accommodation_booking" is blocked
If you want to add a new booking you can do it with calendars.

**Comment by ugintl** [comment]
Here is the screenshot of the entity rules settings. What changes should I make?
![entityrules-batbooking](https://user-images.githubusercontent.com/12570802/60908597-b3b01900-a295-11e9-87ac-3ab56592aafd.png)

Where is calendar?

**Comment by acrollet** [comment]
Generally when access is denied for an admin, it's because it's best to use the specific forms provided by RfA for e.g. making a booking, rather than the default entity form.
