### ISSUE TITLE
Bootstrap overriding  custom css

### ISSUE THREAD

**Issue by ugintl** [Roomify/RfA#410]
I am trying to center an image in a block created using views. I am using custom css, but bootstrap seems to be overriding the css. I found a way to do it within views, but I am not sure it is the right way. I have tried many things, but this is the only way seems to be working.
![slide-withblock](https://user-images.githubusercontent.com/12570802/61131931-ca43b380-a4d3-11e9-83d3-fff41135c4a0.png)

Similar problem happening with the buttons

**Comment by acrollet** [comment]
You may need more specificity in your selectors. You could try adding an id or class to your div and targeting that.
