### ISSUE TITLE
List of the patches applied to this distribution

### ISSUE THREAD

**Issue by ugintl** [Roomify/RfA#411]
Can you please provide a list of patches applied to the distribution? For example like you see on the release page of a drupal distribution on drupal.org

commerce 1.15 is out for a while with lot of fixes, but I do not know what patches you have applied so cannot update

**Comment by acrollet** [comment]
All patches to contrib can be seen in https://github.com/Roomify/RfA/blob/master/drupal-org.make - just search for the module you're interested in.
