### ISSUE TITLE
Properties view mini panel on front page missing styles

### ISSUE THREAD

**Issue by ugintl** [Roomify/RfA#413]
When I put the Available properties grid view mini panel, using blocks ui, on the front page as shown below, it displays without any styles applied to it. Why is that?

On the properties list page all shows fine. I have also tried to target classes and id, but no success.

![available-properties-block](https://user-images.githubusercontent.com/12570802/61453132-c81ba200-a976-11e9-9f19-3ef5082d037a.png)
![available-properties-grid-view](https://user-images.githubusercontent.com/12570802/61453134-cc47bf80-a976-11e9-9278-80bc4e106b08.png)

**Comment by acrollet** [comment]
@ugintl this mini panel was built for the previous RfA theme, so there's no theming for the current theme. We'll probably remove it at some point so if you want to use it, you should copy it to a custom module and apply theming as you like.

**Comment by ugintl** [comment]
The same view has a view pane "Card View". When I visit a node of type "Properties List", it shows like this 

![available-properties-card-view](https://user-images.githubusercontent.com/12570802/61790922-f1827500-ae31-11e9-9b07-53af3f04f090.png)

But when I create a mini-panel of this view pane and put it on the front page, this is how it shows. It seems to loose the css styles. How can I show it exactly like above?

![available-properties-view](https://user-images.githubusercontent.com/12570802/61791052-4b833a80-ae32-11e9-8ed7-c970c435f8ba.png)
