### ISSUE TITLE
Adding alternate payment gateway beyond the supported list

### ISSUE THREAD

**Issue by algodudes** [Roomify/RfA#417]
Is it possible to use any alternate payment gateways apart from the ones listed under Payment Methods menu item.

I could enable the Example payment module and it shows up during checkout, but cannot find any way to configure other enabled payment gateway modules.

**Comment by acrollet** [comment]
Hi @algodudes, you should be able to enable and configure any drupal commerce payment module, using the standard configuration process in the commerce settings. (Settings for modules you install will not appear on the roomify payment settings form.)

**Comment by algodudes** [comment]
Thank you.. Actually that what I also thought. Problem is I am not able to access drupal commerce payment gateway settings page. Tries access it manually using: admin/commerce/config/payment-methods

Still no go. Thanks
![store-config](https://user-images.githubusercontent.com/35414772/65157937-259f9e00-da4f-11e9-8e34-7d41c73e1c2c.jpg)

**Comment by acrollet** [comment]
@algodudes are you logged in as user 1?

**Comment by algodudes** [comment]
Yes

**Comment by acrollet** [comment]
@algodudes is the commerce payment UI module enabled?

**Comment by algodudes** [comment]
Thank you very much... That was the problem. Its all good now.

Thanks and really appreciate your help

**Comment by acrollet** [comment]
I've updated the self-hosted documentation to add a section on using alternative payment gateways.
