### ISSUE TITLE
availability-search page error

### ISSUE THREAD

**Issue by foolfitz** [Roomify/RfA#52]
hi,
after I edited "property owner casa", the top of availability-search (the "Property" link in menu) showed following message:
`Notice: Undefined variable: col_classes in include() (line 28 of /opt/bitnami/apps/drupal/htdocs/sites/all/themes/roomify/roomify_travel/templates/views/properties/views-bootstrap-grid-plugin-style--properties-index--panel-pane-3.tpl.php).`

thank you!

**Comment by salvoscala** [comment]
Hi @foolfitz,
I've tried to download a clean version of the last release and riproduce the issue without fortune.
That variable should be set by the Views Bootstrap module (we use a specific version to fix the issue). Do you use another version of that module or have some other informations that can help us?

Thanks!

**Comment by foolfitz** [comment]
oh! my Views Bootstrap is 7.x-3.1, maybe it was drupal's notification let me update the module!
how can I install the specific version Views Bootstrap again? thank you!

**Comment by salvoscala** [comment]
We use a make file to download contrib modules and this is the version of Views Bootstrap:

projects[views_bootstrap][type] = module
projects[views_bootstrap][download][type] = git
projects[views_bootstrap][download][url] = https://git.drupal.org/project/views_bootstrap.git
projects[views_bootstrap][download][revision] = eee44d0f4f567aef22f7a4bdb7d64e1a715e6449

You can use the drush make command or just download the module that I've attached here ;)

[views_bootstrap.zip](https://github.com/Roomify/RfA/files/691545/views_bootstrap.zip)

**Comment by foolfitz** [comment]
it's ok now, thank you, @salvoscala !
