### ISSUE TITLE
Conversation Booking Guest information storage

### ISSUE THREAD

**Issue by cecrs** [Roomify/RfA#61]

**Comment by salvoscala** [comment]
I think we don't need this because we don't have any customer information during a conversation. If users book from a conversation they have to complete the checkout and create a standard Roomify for Accommodation booking (with order and customer profile).

@cecrs @acrollet

**Comment by salvoscala** [comment]
Done in https://github.com/Roomify/RfA/commit/494b873465f74c3446bf0adaacdb3b0291951384
