### ISSUE TITLE
Colors Missing in Calendar (Rooms9

### ISSUE THREAD

**Issue by ZabosP** [Roomify/RfA#69]
Hello Everyone!

I'm developing a site with rooms module, and if i manage the pricing and the availabiality of the rooms, there are no colors, and prices in the calendar.

Can somebody help me?

Thanks a lot!

**Comment by acrollet** [comment]
Hi there,

if you're talking about the drupal rooms module (https://www.drupal.org/project/rooms) please open an issue at https://www.drupal.org/project/issues/rooms?categories=All

**Comment by ZabosP** [comment]
Thanks for your answer.

Yes, i have the problem with that module, and at drupal.org, there is an opened issue, but there is no usable answer :(

**Comment by acrollet** [comment]
I'm afraid this product does not have anything to do with rooms, can you link the issue you're talking about?

**Comment by ZabosP** [comment]
https://www.drupal.org/node/2835023

**Comment by ZabosP** [comment]
I have the same problem :(

**Comment by acrollet** [comment]
Please comment on that issue with all information you have about your problem, thanks.
